<?php

namespace AppBundle\Repository;

/**
 * ArchivoHistoricoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchivoHistoricoRepository extends \Doctrine\ORM\EntityRepository
{
}
