<?php

namespace AppBundle\Repository;

/**
 * PersonaProyectoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonaProyectoRepository extends \Doctrine\ORM\EntityRepository
{
}
