# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\Persona:
            algorithm: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: AppBundle:Persona

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                username_parameter: _rut
            provider: our_db_provider

    role_hierarchy:
            ROLE_REPRESENTANTE_LEGAL: [ROLE_USER]
            ROLE_TRABAJADOR: [ROLE_REPRESENTANTE_LEGAL, ROLE_CREAR_ARCHIVO]
            ROLE_DIRECTOR: [ROLE_TRABAJADOR, ROLE_CREAR_PROYECTO, ROLE_VER_OTROS_ARCHIVOS]
            ROLE_ADMIN: [ROLE_DIRECTOR, ROLE_CREAR_CUENTA, ROLE_VER_OTROS_PROYECTOS]

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
        #- { path: ^/mis_proyectos, roles: ROLE_USER }
        - { path: ^/nuevo_proyecto, roles: ROLE_CREAR_PROYECTO }
        - { path: ^/register, roles: ROLE_ADMIN }

